name: Run the console app
on: push
jobs:
  build:
    name: Build the console app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'
    - run: dotnet build ./src/Actions.Console/Actions.Console.csproj