name: Run the unit tests
on: push
jobs:
  run:
    name: Run the unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'
    - name: Checkout the repository
      uses: actions/checkout@master
    - name: Run the unit tests
      run: dotnet test ./tst/Actions.UnitTest/Actions.UnitTest.csproj